spring:
  application:
    name: Messaging-App
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <client id>
            client-secret: <client secret>
  data:
    cassandra:
      keyspace-name: <astra db keyspace name>
      username: <client id>
      password: <client secret>
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: <secure connect bundle name>.zip

astra:
  db:
    id: <astra db datacenter id>
    region: <astra db region>
    keyspace: <astra db keyspace name>
    application:
      token: <genetated token> 

